#! /bin/bash
#
# Copyright (c) 2017-2019, AT&T Intellectual Property.  All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header Dataplane
for dp in $(/opt/vyatta/sbin/vyatta-interfaces.pl --show=dataplane)
do header "Interface statistics for $dp"
	time_out "run show interface dataplane $dp"
done

header "Dataplane ARP"
time_out 'run show dataplane statistics arp'

time_out 'run show dataplane arp'

header "Dataplane Routes"

time_out "run show dataplane route"

eval "tables=($(cli-shell-api listActiveNodes protocols static table))"

for table in "${tables[@]}"; do
	header "Table $table"

	time_out "run show dataplane route table $table"
done
