#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header Bonding
for bnd in $(/opt/vyatta/sbin/vyatta-interfaces.pl --show=bonding)
do header "Interface statistics for $bnd"
	time_out "run show interfaces bonding $bnd"
	time_out "run show interfaces bonding $bnd slaves"
done
