#! /bin/bash
#
# Copyright (c) 2018-2019, AT&T Intellectual Property.  All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header Bridging
time_out "run show bridge"

for br in $(/opt/vyatta/sbin/vyatta-interfaces.pl --show=bridge)
do header "Operational bridge state for $br"
	time_out "run show bridge $br spanning-tree brief"
	time_out "run show bridge $br macs"
done
