#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header "ARP Table (Total entries)"
do_cmd run show arp

header Number of incomplete entries in ARP table
do_cmd_header "run show arp | grep -c PENDING"
run show arp | grep -c PENDING
exit 0
