#! /bin/bash
#
# Copyright (c) 2018-2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

if [ ! -d /dev/ipmi0 ]; then
	exit
fi

header BMC

time_out "run show bmc status"

time_out "run show hardware sensor"

# This can take a long time.
time_out_sec 30s "run show hardware sensor sel"
