#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header DHCPV6 Server "$DEFAULT_VRF_NAME"
if cli-shell-api existsActive service dhcpv6-server; then
	header DHCPV6 Server Status "$DEFAULT_VRF_NAME"
	time_out "run show dhcpv6 server status "
	header DHCPV6 Server Leases "$DEFAULT_VRF_NAME"
	time_out "run show dhcpv6 server leases"
else
	echo "DHCPV6 server is not configured"
fi
