#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header DHCPV6 Relay "$DEFAULT_VRF_NAME"
if cli-shell-api existsActive service dhcpv6-relay; then
	header DHCPV6 Relay Status "$DEFAULT_VRF_NAME"
	time_out "run show dhcpv6 relay-agent status "
else
	echo "DHCPV6 Relay is not configured"
fi
