#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header DNS "$DEFAULT_VRF_NAME"
if cli-shell-api existsActive service dns; then
	header DNS Dynamic Status "$DEFAULT_VRF_NAME"
	time_out "run show dns dynamic status"
	header DNS Forwarding Statistics "$DEFAULT_VRF_NAME"
	time_out "run show dns forwarding statistics"
	header DNS Forwarding Nameservers "$DEFAULT_VRF_NAME"	
	time_out "run show dns forwarding nameservers"
else
	echo "DNS is not configured"
fi
