#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header Firewall 
if cli-shell-api existsActive security firewall; then
	header Firewall Summary
	time_out "run show firewall"
	header Firewall Sessions
	time_out "run show session-table"
	header Firewall Session Statistics
	time_out "run show session-table statistics"
else
	echo "Firewall is not configured"
fi
