#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header Traffic Policy
if cli-shell-api existsActive policy qos; then
	header Current Traffic Policies
	time_out "run show queuing"
else
	echo "Traffic-Policy is not configured"
fi
