#! /bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header VRRP
header \''run show vrrp detail'\'
time_out "run show vrrp detail"

header \''run show vrrp statistics'\'
time_out "run show vrrp statistics"

header \''/var/run/vrrpd/vrrp.log'\'
do_cmd cat /var/run/vrrpd/vrrp.log
exit 0
