#! /bin/bash
#
# Copyright (c) 2017-2019, AT&T Intellectual Property.  All rights reserved.
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

eval "vrf_names=($(cli-shell-api listActiveNodes routing routing-instance))"
vrf_names="${vrf_names[@]}"

for vrf_name in $vrf_names; do
	header "routing instance $vrf_name"
	inst="routing-instance $vrf_name"

	time_out "run show dataplane route $inst"

	eval "tables=($(cli-shell-api listActiveNodes routing $inst protocols static table))"

	for table in "${tables[@]}"; do
		header "Table $table"

		time_out "run show dataplane route $inst table $table"
	done
done
